### ISSUE TITLE
Third-party code

### ISSUE THREAD

**Issue by amesbah** [saltlab/CallMeBack#1]
@keheliya be careful with including third-party code in our repositories in this manner. Third-party code should be used as external libs/packages through well-defined dependencies. The repository should only contain our own code written on top of those libs/packages.

Please refactor using this guideline.

**Comment by alexnederlof** [comment]
@amesbah is right. Including 3rd party libs is a bad practice. Use NPM or Bower to manage JS libs.

**Comment by keheliya** [comment]
Hi @amesbah @alexnederlof 
Yes. I'm already using NPM to manage third-party libs. If your concern is regarding this:
https://github.com/saltlab/RoundTrace/tree/master/proxy
it's taken from here:
https://github.com/adobe-research/theseus/tree/master/src/proxy
But I have no way of referring to it via NPM because these are internal code of theseus and not exported. I'll be forking other libraries I have to heavily modify and use (such as fondue, node-theseus). But not the above because they are internal utility functions. Any thoughts on how to handle it better?

**Comment by alexnederlof** [comment]
If it is already a git repo, import it as a git submodule.

**Comment by keheliya** [comment]
Hi @alexnederlof 
Thanks for the tip. But git submodule doesn't allow to have only part of the external repo as a submodule. Isn't it?

**Comment by alexnederlof** [comment]
No it does not. Can't you circumvent it?

**Comment by amesbah** [comment]
Can we close this issue?
